---
name: Subgraph Deploy

# Controls when the action will run.
on:
  push:
    tags:
      - '*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GRAPH_USER: digitalnativeinc
  GRAPH_CLI_VERSION: 0.22.2

jobs:
  subgraph-deploy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - chain: rinkeby
            graph_service: hosted
            workspace: exchange
          - chain: rinkeby
            graph_service: hosted
            workspace: masterchefV2
          - chain: shibuya
            graph_service: private
            graph_url: https://graph.shibuya.standardtech.xyz:4443
            ipfs_url: https://ipfs.shibuya.standardtech.xyz
            workspace: exchange
          - chain: shibuya
            graph_service: private
            graph_url: https://graph.shibuya.standardtech.xyz:4443
            ipfs_url: https://ipfs.shibuya.standardtech.xyz
            workspace: exchange
          # - chain: shiden
          #   graph_service: private
          #   graph_url: https://graph.shiden.standardtech.xyz:4443
          #   ipfs_url: https://ipfs.shiden.standardtech.xyz
          #   workspace: exchange
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set tag
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Yarn - Install
        uses: borales/actions-yarn@v2.3.0
        env:
          CHAIN: ${{ matrix.chain }}
        with:
          cmd: install

      - name: Graph CLI - Auth
        shell: bash
        run: |
          yarn global add @graphprotocol/graph-cli@${{ env.GRAPH_CLI_VERSION }}
          echo "$(yarn global bin)" >> $GITHUB_PATH
          echo "::add-mask::${{ secrets.GRAPH_API_KEY }}"

      - name: Yarn - Prepare Subgraph
        uses: borales/actions-yarn@v2.3.0
        env:
          CHAIN: ${{ matrix.chain }}
        with:
          cmd: prepare

      - name: Yarn - Subgraph Code Generation
        uses: borales/actions-yarn@v2.3.0
        env:
          CHAIN: ${{ matrix.chain }}
        with:
          cmd: workspace ${{ matrix.workspace }} codegen

      - name: Yarn - Deploy Subgraph - Hosted Service
        uses: borales/actions-yarn@v2.3.0
        if: ${{ matrix.graph_service == 'hosted' }}
        env:
          CHAIN: ${{ matrix.chain }}
          GRAPH_URL: https://api.thegraph.com/deploy/
          IPFS_URL: https://api.thegraph.com/ipfs/
        with:
          cmd: workspace ${{ matrix.workspace }} deploy --access-token ${{ secrets.GRAPH_API_KEY }} --version-label ${{ env.TAG }}

      - name: Yarn - Create Subgraph - Private Service
        uses: borales/actions-yarn@v2.3.0
        if: ${{ matrix.graph_service == 'private' }}
        env:
          CHAIN: ${{ matrix.chain }}
          GRAPH_URL: ${{ matrix.graph_url }}
          IPFS_URL: ${{ matrix.ipfs_url }}
        with:
          cmd: workspace ${{ matrix.workspace }} create-subgraph --version-label ${{ env.TAG }}

      - name: Yarn - Deploy Subgraph - Private Service
        uses: borales/actions-yarn@v2.3.0
        if: ${{ matrix.graph_service == 'private' }}
        env:
          CHAIN: ${{ matrix.chain }}
          GRAPH_URL: ${{ matrix.graph_url }}
          IPFS_URL: ${{ matrix.ipfs_url }}
        with:
          cmd: workspace ${{ matrix.workspace }} deploy --version-label ${{ env.TAG }}
